name: RotatE_RGCN Training and Evaluation Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        # Installer PyTorch (version 2.1.0 compatible avec PyTorch Geometric 2.6.1)
        pip install torch==2.1.0+cpu
        
        # Installer PyTorch Geometric et ses dépendances compatibles
        pip install torch-geometric==2.6.1 -f https://data.pyg.org/whl/torch-2.1.0+cpu.html
        pip install torch-scatter==2.1.2+pt21cpu
        pip install torch-cluster==1.6.3+pt21cpu
        pip install torch-sparse==0.6.18+pt21cpu
        pip install torch-spline-conv==1.2.2+pt21cpu

        # Installer les autres dépendances nécessaires
        pip install py2neo pandas sentence-transformers fuzzywuzzy
        pip install torch-geometric torch-max-mem
        pip install gym gymnasium stable_baselines3 scikit-learn optuna
        pip install matplotlib seaborn tqdm

    - name: Verify installations
      run: |
        # Vérification de l'installation des dépendances
        pip list
        python -c "import torch; print(torch.__version__)"
        python -c "import torch_geometric; print(torch_geometric.__version__)"

  run_pipeline:
    runs-on: ubuntu-latest
    needs: install_dependencies

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run RotatE_RGCN pipeline
      run: |
        # Exécuter le script principal
        python cskg/rotatE_Rgcn.py
